name: Node CI

on: [push]

jobs:
  build-n-test:
    name: Build and test
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install deps
      run: yarn install
    - name: Build js
      run: yarn build
    - name: Run tests
      run: yarn test --coverage

    - name: Upload built package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: dist


  publish:
    runs-on: ubuntu-18.04
    needs: build-n-test

    steps:
    - name: Download built package
      uses: actions/download-artifact@v1.0.0
      with:
        name: dist
    - run: ls dist